### ISSUE TITLE
Support yarn v2 berry

### ISSUE THREAD

**Issue by remorses** [Bnaya/typescript-monorepo-toolkit#4]
Yarn v2 removed the command `yarn workspaces info`

I can work on a pull request to add support for yarn v2 and the future release of npm workspaces

i will implement an unviersal `yarn workspaces info` library on a separate package

**Comment by Bnaya** [comment]
Hey @remorses thank you very much for your involvement!
Will it work for you we make monorepo with this utility and your workspace-info? (I will make you also collaborator of course)   
or even create separate org for that

**Comment by remorses** [comment]
Is it a problem to keep it as a separate package? It’s scope is larger than the typescript toolkit
The code is here https://github.com/remorses/workspace-info

If you worry about it’s correctness I already tested it on a monorepo with 250 packages

**Comment by remorses** [comment]
Thank you for merging 😊
